<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOUZkhlm\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOUZkhlm/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerOUZkhlm.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerOUZkhlm\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerOUZkhlm\App_KernelProdContainer([
    'container.build_hash' => 'OUZkhlm',
    'container.build_id' => 'c217e2c7',
    'container.build_time' => 1725839876,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOUZkhlm');
