<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBFjpDzQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBFjpDzQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBFjpDzQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBFjpDzQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBFjpDzQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'BFjpDzQ',
    'container.build_id' => 'd6fc66dc',
    'container.build_time' => 1725843536,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBFjpDzQ');
